version: '2.1'

services:
  anthias-wifi-connect:
    build:
      context: .
      dockerfile: docker/Dockerfile.wifi-connect
    depends_on:
      - anthias-viewer
    environment:
      PORTAL_LISTENING_PORT: 8000
      CHECK_CONN_FREQ: 10
      PORTAL_SSID: 'Anthias WiFi Connect'
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/run/dbus/system_bus_socket'
    network_mode: host
    privileged: true

  anthias-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    restart: always
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Berlin
    volumes:
      - balena-data:/data
    labels:
      io.balena.features.supervisor-api: '1'

  anthias-viewer:
    build:
      context: .
      dockerfile: docker/Dockerfile.viewer
    restart: always
    privileged: true
    shm_size: 512mb
    mem_limit: 512m
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - PORT=80
      - NOREFRESH=1
      - LISTEN=anthias-nginx
    volumes:
      - balena-data:/data
    labels:
      io.balena.features.supervisor-api: '1'

  anthias-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    restart: always
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    volumes:
      - balena-data:/data

  anthias-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    restart: always
    depends_on:
      - anthias-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - balena-data:/data
    labels:
      io.balena.features.supervisor-api: '1'

  redis:
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    restart: always
    volumes:
      - redis-data:/var/lib/redis

  anthias-nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - anthias-server
      - anthias-websocket
    environment:
      - HOME=/data
    volumes:
      - balena-data:/data:ro

volumes:
  balena-data:
  redis-data:
