version: '2.1'

services:
  anthias-server:
    image: screenly/anthias-server:latest-aarch64
    restart: always
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - balena-data:/data
    labels:
      io.balena.features.supervisor-api: '1'

  anthias-viewer:
    image: screenly/anthias-viewer:latest-aarch64
    restart: always
    privileged: true
    shm_size: 512mb
    mem_limit: 512m
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - PORT=80
      - NOREFRESH=1
      - LISTEN=anthias-nginx
    volumes:
      - balena-data:/data
    labels:
      io.balena.features.supervisor-api: '1'

  anthias-websocket:
    image: screenly/anthias-websocket:latest-aarch64
    restart: always
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    volumes:
      - balena-data:/data

  anthias-celery:
    image: screenly/anthias-celery:latest-aarch64
    restart: always
    depends_on:
      - anthias-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - balena-data:/data
    labels:
      io.balena.features.supervisor-api: '1'

  redis:
    image: screenly/anthias-redis:latest-aarch64
    restart: always
    volumes:
      - redis-data:/var/lib/redis

  anthias-nginx:
    image: screenly/anthias-nginx:latest-aarch64
    restart: always
    ports:
      - "80:80"
    depends_on:
      - anthias-server
      - anthias-websocket
    environment:
      - HOME=/data
    volumes:
      - balena-data:/data:ro

volumes:
  balena-data:
  redis-data:
